;;; globale Definitionen
;;; werden in verschiedenen Dateien bedingt eingebunden

CAOS_ARGN:	equ 0xb781
CAOS_ARG1:	equ 0xb782
;CAOS_ARG2:	equ 0xb784
;CAOS_ARG3:	equ 0xb786
;CAOS_ARG4_9:	equ 0xb788
;CAOS_CURSO:	equ 0xb7a0
;CAOS_COLOR:	equ 0xb7a3
CCTL0:		equ 0xb7a6
SUTAB:		equ 0xb7b0
;CAOS_HOR:	equ 0xb7d3
;CAOS_VERT:	equ 0xb7d5
;CAOS_FARB:	equ 0xb7d6
;SUBALT:		equ 0xb7fe
PV1:		equ 0xf003
;ISRO:		equ 0x08
;ISRI:		equ 0x0a
AHEX:		equ 0x1c
ZSUCH:		equ 0x1d
OSTR:		equ 0x23

fileName:	equ 0x0000		; "neue Vereinbarung" zw. Pascal und PasEx2
;fileExt:	equ 0x0008    		; ABER: ist nicht 0-terminiert!
